package presenter;

import model.Medicine;

public enum EVENTS {

    C_DIALOG_REGISTER_PET,
    C_DIALOG_REGISTER_DOC,
    C_SCHEDULE_APPOINTMENT,
    C_SPANISH_LANGUAGE,
    C_ENGLISH_LANGUAGE,
    C_ADD_NEW_DOCTOR,
    C_ADD_NEW_PET,
    C_CANCEL,
    C_SHOW_PANEL_GRAPHICS,
    C_SHOW_PANEL_TABLES,
    C_SHOW_TABLE_MEDICINE_RARE,
    C_SHOW_LIST_OF_DOCTORS,
    C_SHOW_LIST_OF_PETS_AND_OWNER,
    C_SHOW_LIST_APPOINTMENT,
    C_BACK_IMAGE_BANNER,
    C_NEXT_IMAGE_BANNER,
    C_SHOW_HOMEPAGE,
    C_ADD_NEW_APPOINTMENT,
    C_SHOW_TABLE_APPOINTMENT_BY_CATEGORY,
    C_SHOW_TABLE_PETS_BY_CATEGORY,
    C_SHOW_TABLE_DOCTORS_BY_CATEGORY,
    C_SHOW_GRAPHICS_ONE,
    C_SHOW_TABLE_MEDICINE_BY_SPECIE,
    C_SHOW_GRAPHICS_TWO,
    C_SHOW_GRAPHICS_THREE,
    C_SHOW_GRAPHICS_FOUR,
    C_SHOW_GRAPHICS_FIVE,
    C_SHOW_GRAPHICS_SIX,
    C_DELETE_PPOINTMENT,
    C_DELETE_MEDICINE,
    C_DELETE_DOCTOR,
    C_DELETE_PET,
}
